In [1]:
import re


import pandas as pd
from astropy.coordinates import SkyCoord
from astropy.time import Time
from astroquery.jplhorizons import Horizons

In [2]:
df = pd.read_csv('D:\Project\Earthquake\Comets\AllAsteroid.csv')
df

,Time,SUN_X,SUN_Y,SUN_Z,199_X,199_Y,199_Z,299_X,299_Y,299_Z,...,Dinkinesh_Z,20065803_X,20065803_Y,20065803_Z,Gaspra_X,Gaspra_Y,Gaspra_Z,Ceres_X,Ceres_Y,Ceres_Z
0,1/1/2000,-0.007140,-0.002644,-0.000921,-0.147852,-0.400633,-0.198918,-0.725770,-0.039682,0.027895,...,0.706154,99.000000,99.000000,99.000000,-1.720290,1.478228,0.478057,-2.384673,0.547941,0.742252
1,1/2/2000,-0.007134,-0.002651,-0.000924,-0.126483,-0.405565,-0.203767,-0.724966,-0.058180,0.019523,...,0.708922,99.000000,99.000000,99.000000,-1.728906,1.472102,0.474910,-2.388252,0.538089,0.738344
2,1/3/2000,-0.007129,-0.002657,-0.000927,-0.104766,-0.409323,-0.208026,-0.723594,-0.076634,0.011134,...,99.000000,99.000000,99.000000,99.000000,-1.737482,1.465942,0.471751,-2.391788,0.528228,0.734423
3,1/4/2000,-0.007124,-0.002664,-0.000930,-0.082765,-0.411897,-0.211682,-0.721654,-0.095029,0.002736,...,0.714377,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,-2.395282,0.518357,0.730490
4,1/5/2000,99.000000,99.000000,99.000000,-0.060543,-0.413279,-0.214724,-0.719149,-0.113351,-0.005665,...,0.717062,99.000000,99.000000,99.000000,-1.754509,1.453517,0.465400,-2.398733,0.508476,0.726543
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8775,2024-01-10,-0.007924,-0.002808,-0.000989,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,...,-0.628575,-1.543961,-1.510923,-0.590110,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000
8776,2024-01-11,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,...,-0.632451,-1.536418,-1.515578,-0.592697,-1.848275,-1.594800,-0.788289,99.000000,99.000000,99.000000
8777,2024-01-12,-0.007914,-0.002821,-0.000994,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,...,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,-1.004206,-2.412090,-0.934540
8778,2024-01-13,99.000000,99.000000,99.000000,-0.402289,-0.112684,-0.018807,-0.658965,-0.300613,-0.093800,...,-0.640160,99.000000,99.000000,99.000000,-1.833540,-1.607351,-0.792329,99.000000,99.000000,99.000000
8779,2024-01-14,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,...,99.000000,-1.513543,-1.529300,-0.600365,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000

In [11]:
# ch_data = df.iloc[:, 1:]
ch_data = df.drop(['-74_X', '-74_Y', '-74_Z', '-49_X', '-49_Y', '-49_Z','-490_X', '-490_Y', 
                        '-490_Z', '-255_Z', '-255_Y', '-255_X' , '2000016_X', '2000016_Y', '2000016_Z',
                        '20065803_X', '20065803_Y', '20065803_Z', '-64_X', '-64_Y', '-64_Z'], axis=1)

def parse_date(value):
    try:
        return pd.to_datetime(value, format='%m/%d/%Y')
    except ValueError:
        try:
            return pd.to_datetime(value, format='%Y-%m-%d')
        except ValueError:

            return pd.NaT
ch_data['Time'] = ch_data['Time'].apply(parse_date)

ch_data['Time'].fillna('1900-01-01', inplace=True)

ch_data['Time'] = pd.to_datetime(ch_data['Time']).dt.strftime('%Y-%m-%d')
ch_data.to_csv('AllAsteroidV1.csv')
# ch_data = ch_data.iloc[:, 1:]
# Ti = ch_data.pop('Time')
ch_data

,Time,SUN_X,SUN_Y,SUN_Z,199_X,199_Y,199_Z,299_X,299_Y,299_Z,...,90000855_Z,Dinkinesh_X,Dinkinesh_Y,Dinkinesh_Z,Gaspra_X,Gaspra_Y,Gaspra_Z,Ceres_X,Ceres_Y,Ceres_Z
0,2000-01-01,-0.007140,-0.002644,-0.000921,-0.147852,-0.400633,-0.198918,-0.725770,-0.039682,0.027895,...,-0.602941,1.023883,1.519507,0.706154,-1.720290,1.478228,0.478057,-2.384673,0.547941,0.742252
1,2000-01-02,-0.007134,-0.002651,-0.000924,-0.126483,-0.405565,-0.203767,-0.724966,-0.058180,0.019523,...,-0.601298,1.012587,1.524985,0.708922,-1.728906,1.472102,0.474910,-2.388252,0.538089,0.738344
2,2000-01-03,-0.007129,-0.002657,-0.000927,-0.104766,-0.409323,-0.208026,-0.723594,-0.076634,0.011134,...,99.000000,99.000000,99.000000,99.000000,-1.737482,1.465942,0.471751,-2.391788,0.528228,0.734423
3,2000-01-04,-0.007124,-0.002664,-0.000930,-0.082765,-0.411897,-0.211682,-0.721654,-0.095029,0.002736,...,-0.598007,0.989876,1.535763,0.714377,99.000000,99.000000,99.000000,-2.395282,0.518357,0.730490
4,2000-01-05,99.000000,99.000000,99.000000,-0.060543,-0.413279,-0.214724,-0.719149,-0.113351,-0.005665,...,-0.596360,0.978463,1.541062,0.717062,-1.754509,1.453517,0.465400,-2.398733,0.508476,0.726543
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8775,2024-01-10,-0.007924,-0.002808,-0.000989,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,...,99.000000,-1.792371,-1.380605,-0.628575,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000
8776,2024-01-11,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,...,99.000000,-1.786093,-1.388578,-0.632451,-1.848275,-1.594800,-0.788289,99.000000,99.000000,99.000000
8777,2024-01-12,-0.007914,-0.002821,-0.000994,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,...,-1.141751,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,-1.004206,-2.412090,-0.934540
8778,2024-01-13,99.000000,99.000000,99.000000,-0.402289,-0.112684,-0.018807,-0.658965,-0.300613,-0.093800,...,-1.142165,-1.773413,-1.404428,-0.640160,-1.833540,-1.607351,-0.792329,99.000000,99.000000,99.000000
8779,2024-01-14,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,...,-1.142571,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000

In [7]:
ch_data[ch_data == 99] = 0
ch_data

,SUN_X,SUN_Y,SUN_Z,199_X,199_Y,199_Z,299_X,299_Y,299_Z,399_X,...,90000855_Z,Dinkinesh_X,Dinkinesh_Y,Dinkinesh_Z,Gaspra_X,Gaspra_Y,Gaspra_Z,Ceres_X,Ceres_Y,Ceres_Z
0,-0.007140,-0.002644,-0.000921,-0.147852,-0.400633,-0.198918,-0.725770,-0.039682,0.027895,-0.175677,...,-0.602941,1.023883,1.519507,0.706154,-1.720290,1.478228,0.478057,-2.384673,0.547941,0.742252
1,-0.007134,-0.002651,-0.000924,-0.126483,-0.405565,-0.203767,-0.724966,-0.058180,0.019523,-0.192879,...,-0.601298,1.012587,1.524985,0.708922,-1.728906,1.472102,0.474910,-2.388252,0.538089,0.738344
2,-0.007129,-0.002657,-0.000927,-0.104766,-0.409323,-0.208026,-0.723594,-0.076634,0.011134,-0.210024,...,0.000000,0.000000,0.000000,0.000000,-1.737482,1.465942,0.471751,-2.391788,0.528228,0.734423
3,-0.007124,-0.002664,-0.000930,-0.082765,-0.411897,-0.211682,-0.721654,-0.095029,0.002736,-0.227107,...,-0.598007,0.989876,1.535763,0.714377,0.000000,0.000000,0.000000,-2.395282,0.518357,0.730490
4,0.000000,0.000000,0.000000,-0.060543,-0.413279,-0.214724,-0.719149,-0.113351,-0.005665,-0.244122,...,-0.596360,0.978463,1.541062,0.717062,-1.754509,1.453517,0.465400,-2.398733,0.508476,0.726543
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8775,-0.007924,-0.002808,-0.000989,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.326220,...,0.000000,-1.792371,-1.380605,-0.628575,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8776,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.342730,...,0.000000,-1.786093,-1.388578,-0.632451,-1.848275,-1.594800,-0.788289,0.000000,0.000000,0.000000
8777,-0.007914,-0.002821,-0.000994,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.141751,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.004206,-2.412090,-0.934540
8778,0.000000,0.000000,0.000000,-0.402289,-0.112684,-0.018807,-0.658965,-0.300613,-0.093800,-0.375431,...,-1.142165,-1.773413,-1.404428,-0.640160,-1.833540,-1.607351,-0.792329,0.000000,0.000000,0.000000
8779,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.391611,...,-1.142571,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [8]:
object_planet = ['SUN', '199', '299', '399', '301', '-74', '599', '699', '433', 'Eros', 'Orus', '-49',
                       '-490', '-255', '2000016', '90000188', '90000190', '90000191', 
                        'Leucus', 'Eurybates','Polymele', 'Vesta', 'Mathilde', 'Lutetia', 'Donaldjohanson','Braille', 'Annefrank', 
                        'Bennu', 'Itokawa', '-64', 'Apophis', 'Ryugu', '-122911', 'Patroclus', 
                        '90000855', 'Dinkinesh', '20065803' , 'Gaspra', 'Ceres']

def calculate_position(obj, time):
    """
    Args : 
        obj     : obj name str
        time    : time (utc) format yyyy-mm-dd
    """
    epoch = Time(time)
    q = Horizons(obj, location='@0', epochs=epoch.tdb.jd)
    tab = q.vectors(refplane='earth')
    c = SkyCoord(tab['x'].quantity, tab['y'].quantity, tab['z'].quantity,
                representation_type='cartesian', frame='icrs',
                obstime=epoch)
    result = str(c)
    matches = re.findall(r'-?\d+\.\d+', result)
    result_list = [float(match) for match in matches]
    return result_list

In [13]:
data= calculate_position('SUN', '2020-06-12')
data

[-1.76701223, -1.41230515, -0.64399237]